locales/en/apgames.json, src/games/accasta.ts, src/games/amazons.ts, src/games/archimedes.ts, src/games/ceph.ts, src/games/courtesan.ts, src/games/index.ts, src/games/manalath.ts, src/games/quagmire.ts, src/games/tintas.ts
Implements experimental game Quagmire for AbstractPlay
=> Implements quagmire

src/games/scaffold.ts
There's now a much smarter algorithm for follow-up move detection in Scaffold such that the delay is acceptable now. The multimove notation is also updated to use commas instead of dashes.
=> More efficient algorithm for Scaffold.

src/games/slither.ts
These optimisations are not drastic improvements in performance but they're low-hanging fruits.
=> Some simple optimisations for Slither

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/lielow.ts
Added [Lielow](https://boardgamegeek.com/boardgame/349408/lielow) by Michael Amundsen and Alek Erickson.
=> Added Lielow

locales/en/apgames.json, src/games/index.ts, src/games/trike.ts
Added [Trike](https://boardgamegeek.com/boardgame/307379/trike). The designer specifically requested the addition of sizes 11 and 15 compared to BGA implementation.
=> Added Trike

src/games/iqishiqi.ts
Lucky I found this before the edge case happened in any game. The check for getting the neutral piece into the goal should happen before the check for stalemate.
=> Iqishiqi: Win condition fix

locales/en/apgames.json, locales/en/apresults.json, src/games/furl.ts, src/games/index.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
This is another game that I've been very interested in, [Furl](https://boardgamegeek.com/boardgame/325422/furl). I've added "furl" and "unfurl" move results to represent this mechanism.
=> Added Furl

locales/en/apgames.json, src/games/furl.ts
Fixed annotations, and made game messages clearer so that hopefully it becomes more feasible to learn the rules just by reading the error messages.
Also tried some shading for the goal cells. If it compromises the aesthetics too much, do suggest better approaches.
=> Furl: Finishing touches

locales/en/apgames.json, src/games/havannah.ts, src/games/index.ts
Adding classic [Havannah](https://boardgamegeek.com/boardgame/2759/havannah). Default board size is 8, but I added 4, 6 and 10 to go with it.
=> Added Havannah

locales/en/apgames.json, src/games/index.ts, src/games/tumbleweed.ts
Rudimentary implementation of [Tumbleweed](https://boardgamegeek.com/boardgamedesigner/126470/mike-zapawa). Few things may require testing like the pie rule and the scoring.
=> Added Tumbleweed

locales/en/apgames.json, locales/en/apresults.json, src/games/iqishiqi.ts, src/games/slither.ts
Adding "INITIAL_INSTRUCTIONS" for Hex, and fixing some other strings that bothered me for a while while I'm at it 😄
=> Some miscellaneous fixes in game strings.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/meridians.ts
Adding [Meridians](https://boardgamegeek.com/boardgame/333775/meridians). Designer is OK with rotated board and custom notation.
=> Added Meridians

src/games/meridians.ts, src/games/tumbleweed.ts
Fix Meridians capture and missing "pass" messages in Tumbleweed.
=> Fix Meridians and Tumbleweed

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/mattock.ts
Add the game [Mattock](https://boardgamegeek.com/boardgame/320505/mattock).
=> Added Mattock.

src/games/mattock.ts
Thanks for quickly merging the previous PR. Found a bunch of issues to fix.
Only thing that may be questionable still is the two shades of grey used in this game. Let's see if it works in dark mode.
=> Mattock: Fixed issues

locales/en/apgames.json, src/games/mattock.ts
Added missing condition that caused the blocked-cell detector to be overly sensitive.
Also removed the auto-commit of pass because it seems to cause issues in the actual site for freestyle games. It worked for the local playground though!
=> Mattock: more fixes

locales/en/apgames.json, src/games/catchup.ts, src/games/index.ts
Fixing some issues with Catchup. I've added a `permissive` flag and a `sameMove` function, but the clicks are actually handled a bit more robustly for this game in particular, which ensures maximal consistency.
=> Catchup: Fixes

locales/en/apgames.json, src/games/blooms.ts, src/games/catchup.ts, src/games/veletas.ts
Blooms: Added key like Manalath
Catchup: Remove list generation
Veletas: Some misc fixes
=> Fixes in Blooms, Catchup and Veletas

src/games/blooms.ts, src/games/catchup.ts, src/games/veletas.ts
Minor validation adjustment in Catchup, and click handling in Blooms.
Added missing rule in Veletas.
=> More fixes in Blooms, Catchup and Veletas

locales/en/apgames.json, src/games/index.ts, src/games/mimic.ts
Mostly these changes are an effort to prevent a player from immediately undoing their opponent's move.
=> Some fixes for Mimic

locales/en/apgames.json, src/games/gess.ts
The changes are as per discussion in the AP discord.
=> Gess: Allow moving centre of a piece to edge, and some other improvements.

src/games/veletas.ts
I was only checking for trapped shooters in the LoS of the block piece when I needed to also check it for the shooter's new location. I've now modified it so that it checks all shooters because the algorithm is already very efficient. Also added some comments because it took me a few seconds to remember what the function was doing.
=> Veletas: Fix to `getTrapped` algorithm.

locales/en/apgames.json, src/games/veletas.ts
=> Veletas: Add random variant

locales/en/apgames.json, src/games/cannon.ts
If a piece can be captured by cannon fire, it is subtly highlighted.
=> Cannon: Add piece highlight for threats by cannon fire

locales/en/apgames.json, locales/en/apresults.json, src/games/conhex.ts, src/games/index.ts
Adding [ConHex](https://boardgamegeek.com/boardgame/10989/conhex). Finally got to put the beautiful geometry that you've created in the renderer to use. I don't know if there's a more elegant way to code this, but I have something that works for arbitrary board sizes.
I have seriously considered making the default board size 15x15 instead of the 11x11, but alas, I am not bold enough to do that.
=> Added ConHex.

locales/en/apgames.json, src/games/veletas.ts
Turn's out I missed Luis' proposal to further simplify the random variant so that the first move is just a normal move. There has not been any games with this variant started on the prod server, so I'm going to quickly merge this fix to main.
=> Veletas: Fix random variant.

locales/en/apgames.json, locales/en/apresults.json, src/games/_base.ts, src/games/index.ts, src/games/twixt.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Adding the game [Twixt](https://boardgamegeek.com/boardgame/949/twixt). I don't know if there's a simpler way, but the mechanism for adding and removing links ended up becoming quite complicated. Twixt PP is added as a variant.
=> Added Twixt

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/reversi.ts
Adding Reversi with a few popular variants.
=> Added Reversi.

src/games/reversi.ts
=> Reversi: reverse numbers. (#93)

src/games/tafl.ts
This happens quite often. Didn't think that the framework allows this previously.
=> Hnefatafl: allow both players to simultaneously be in check.

locales/en/apgames.json, locales/en/apresults.json, src/games/blockade.ts, src/games/index.ts
Adding the game [Blockade](https://boardgamegeek.com/boardgame/2559/blockade) with a couple of interesting rule variations. I could not figure out an optimised way to reduce the movelist by checking if a placed wall blocks the path from a player's piece to a goal, so clicking random moves will occasionally result in illegal moves. Still better than having no movelist.
=> Added Blockade.

locales/en/apgames.json, locales/en/apresults.json, package-lock.json, src/games/ccorridor.ts, src/games/index.ts
Making use of the Cairo Collinear geometry with [Cairo Corridor](https://boardgamegeek.com/boardgame/137173/cairo-corridor). I don't know what's the right procedure, but I up-ed the version of the renderer in the package-lock.json.
=> Added Cairo Corridor.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/saltire.ts
Adding the game [Saltire](https://boardgamegeek.com/boardgame/402546/saltire).
=> Adding Saltire.

locales/en/apgames.json, locales/en/apresults.json, src/games/connecticut.ts, src/games/index.ts
Added [Connecticut](https://boardgamegeek.com/boardgame/297319/connecticut).
=> Added Connecticut

locales/en/apgames.json
As per designer request, I'm adding the basic variant where supercuts are irrelevant.
=> Saltire: Add basic variant.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/quax.ts
Adding [Quax](https://boardgamegeek.com/boardgame/36804/quax).
=> Added Quax.

locales/en/apgames.json, src/games/halfcut.ts, src/games/index.ts
As per the discussion from #114, we shall add Halfcut as its own game with Clearcut as a variant.
=> Adding Halfcut as its own game, with Clearcut as a variant.

locales/en/apgames.json, locales/en/apresults.json, src/games/connect6.ts, src/games/gomoku.ts, src/games/in_a_row/InARowBase.ts, src/games/index.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Still a work in progress, but I thought I should try to have a look at some of these changes in the dev server. Gomoku and Connect6 are added. Renju is still ongoing, but the fundamental checks for forbidden points is already implemented in the `InARowBase`.
=> Adding Gomoku and Connect6

locales/en/apgames.json, locales/en/apresults.json, src/games/connect6.ts, src/games/gomoku.ts, src/games/in_a_row/InARowBase.ts, src/games/index.ts, src/games/pente.ts, src/games/renju.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Adding Renju, together with four popular Renju-specific openings. This is very hacky, so let's see how it goes. There's a bunch of other updates to the other in-a-row games to unify the implementation and polish things up.
=> Added Renju

locales/en/apgames.json, locales/en/apresults.json, src/games/connect6.ts, src/games/in_a_row/InARowBase.ts, src/games/index.ts, src/games/irensei.ts, src/games/pente.ts, src/games/renju.ts
Add [Irensei](https://boardgamegeek.com/boardgame/48871/irensei), plus a bunch of other misc fixes in the family of games.
=> Add Irensei

locales/en/apgames.json, src/games/index.ts, src/games/sponnect.ts
Adding [Sponnect](https://boardgamegeek.com/boardgame/113670/sponnect), simpler connection game before I attempt Akron.
=> Add Sponnect.

locales/en/apgames.json, locales/en/apresults.json, src/games/akron.ts, src/games/index.ts
Adding [Akron](https://boardgamegeek.com/boardgame/10889/akron). Don't know which are the right board sizes yet, so just going with 6, 8, 10 for now.
=> Add Akron.

locales/en/apgames.json, src/games/index.ts, src/games/margo.ts
Adding [Margo](https://boardgamegeek.com/boardgame/24923/margo). Board sizes here are known because they're specified in the Margo book (http://cambolbro.com/games/margo/margo-basics-41.pdf).
Todo still: chained revealed captures as specified in appendix A of the book.
=> Add Margo.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/upperhand.ts
Adding [Upper Hand](https://boardgamegeek.com/boardgame/4545/upper-hand). Looks like another territorial stacking ball game that's playable on a large board.
=> Add Upper Hand.

locales/en/apgames.json, src/games/connect6.ts, src/games/in_a_row/InARowBase.ts
Variants that a strong connect6 player requested and are quite trivial to implement.
=> Connect6: Add collinear connect6 and non-collinear connect5.

locales/en/apresults.json, src/games/_base.ts, src/games/acity.ts, src/games/breakthrough.ts, src/games/byte.ts, src/games/chase.ts, src/games/entropy.ts, src/games/epam.ts, src/games/fanorona.ts, src/games/fendo.ts, src/games/fnap.ts, src/games/focus.ts, src/games/homeworlds.ts, src/games/irensei.ts, src/games/lielow.ts, src/games/margo.ts, src/games/mvolcano.ts, src/games/pigs.ts, src/games/strings.ts, src/games/tafl.ts, src/games/tumbleweed.ts, src/games/upperhand.ts, src/games/veletas.ts, src/games/volcano.ts
The main motivation is that if a game ended via repetition, it might not actually be that obvious what happened. Also, Hnefatafl has multiple win condition, so it might be helpful to spell out why the game ended.
=> Add a workflow to provide a reason for EoG.

locales/en/apgames.json, src/games/index.ts, src/games/oust.ts
Adding [Oust](https://boardgamegeek.com/boardgame/30936/oust).
=> Adding Oust.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/susan.ts
Add [Susan](https://boardgamegeek.com/boardgame/26135/susan).
=> Add Susan.

locales/en/apgames.json, src/common/graphs/square-orth.ts, src/games/index.ts, src/games/pletore.ts
Also adds some utility functions to the SquareOrthGraph implementation.
=> Implements Pletore

locales/en/apgames.json, locales/en/apresults.json, src/games/_base.ts, src/games/anache.ts, src/games/index.ts
Adding the game [Anache](https://boardgamegeek.com/thread/3236933/anache-a-promising-new-abstract-from-a-promising-n). This is a complex one...
=> Add Anache

locales/en/apgames.json, src/games/index.ts, src/games/spline.ts
Adding [Spline+](https://boardgamegeek.com/boardgame/109044/spline-plus).
=> Add Spline+.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/spire.ts, src/games/sploof.ts, src/games/spree.ts
Add some popular Shibumi games: [Sploof](https://boardgamegeek.com/boardgame/114188/sploof), [Spire](https://boardgamegeek.com/boardgame/113641/spire) and [Spree](https://boardgamegeek.com/boardgame/114263/spree).
=> Add Sploof, Spire and Spree.

locales/en/apgames.json, src/common/graphs/hex-cone.ts, src/common/graphs/index.ts, src/games/conect.ts, src/games/index.ts
Adding the game [Connect](https://www.marksteeregames.com/Conect_rules.pdf).
=> Adding Conect.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/slyde.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Adding [Slyde](https://boardgamegeek.com/boardgame/308111/slyde).
=> Adding Slyde.

locales/en/apgames.json, locales/en/apresults.json, src/common/graphs/hextri.ts, src/games/index.ts, src/games/volo.ts
Another classic, [Volo](https://boardgamegeek.com/boardgame/83283/volo).
=> Adding Volo.

locales/en/apgames.json, src/games/gonnect.ts, src/games/index.ts
Adding [Gonnect](https://boardgamegeek.com/boardgame/12146/gonnect).
=> Adding Gonnect.

locales/en/apgames.json, locales/en/apresults.json, src/games/acity.ts, src/games/ataxx.ts, src/games/exxit.ts, src/games/index.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Adding [Ataxx](https://boardgamegeek.com/boardgame/91313/ataxx). We also have the hexagonal geometry as a variant. Blocked cells are supported, but I don't know which configurations to enable, so for the time being, we'll just have the default variants where are no blocking cells.
=> Adding Ataxx.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/majorities.ts
Adding [Majorities](https://boardgamegeek.com/boardgame/84153/majorities).
=> Adding Majorities.

locales/en/apgames.json, src/games/rootbound.ts
Fixing the score display during the mid-game and adding an implementation note
=> Root Bound: Fixes

locales/en/apgames.json, locales/en/apresults.json, src/games/buku.ts, src/games/index.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Adding 2D sowing the game [Buku](https://mancala.fandom.com/wiki/Buku). The game doesn't have a BGG page, but David Ploog brought some attention to it in his game writeup.
=> Adding Buku.

src/games/tritium.ts
UX improvement from player feedback
=> Tritium: added visual cue to selected piece

src/games/tritium.ts
This makes the visuals clearer, and simplifies the piece selection code 😄
=> Tritium: stack multiple flags in the sidebar together

src/games/tritium.ts
=> Tritium: code cleanup

locales/en/apgames.json, src/games/index.ts, src/games/shifty.ts
Adding a forgotten game, [Shifty](https://boardgamegeek.com/boardgame/124313/shifty)!
=> Adding Shifty.

locales/en/apgames.json, locales/en/apresults.json, src/common/graphs/hex-slanted.ts, src/games/index.ts, src/games/lox.ts, src/games/query.ts, src/schemas/moveresults.d.ts, src/schemas/moveresults.json
Adding two Christian Freeling connection games: [Lox](https://www.mindsports.nl/index.php/the-pit/1212-lox) and [Query](https://mindsports.nl/index.php/the-pit/548-query).
=> Adding Lox and Query.

locales/en/apgames.json, src/games/connections.ts, src/games/index.ts
Adding [Connections](https://boardgamegeek.com/boardgame/3370/connections).
=> Adding Connections.

locales/en/apgames.json, locales/en/apresults.json, src/games/index.ts, src/games/resolve.ts
Adding the game [Resolve](https://boardgamegeek.com/boardgame/314106/resolve).
=> Adding Resolve.

locales/en/apgames.json, locales/en/apresults.json, package-lock.json, src/common/graphs/onyx.ts, src/games/index.ts, src/games/onyx.ts
Adding [Onyx](https://boardgamegeek.com/boardgame/11375/onyx).
=> Adding Onyx.

locales/en/apgames.json, src/games/alta.ts, src/games/index.ts
Adding [Alta](https://boardgamegeek.com/boardgame/40658/alta).
=> Adding Alta.

locales/en/apgames.json, locales/en/apresults.json, src/common/index.ts, src/common/unbounded-square-board.ts, src/games/_base.ts, src/games/index.ts, src/games/trax.ts
Adding the game [Trax](https://boardgamegeek.com/boardgame/748/trax). Been stalling for too long, but finally got around to actually getting it done. The notation in Trax is quite bizarre, so it took a while to figure out a reasonable way to structure the code.
I added an `UnboundedSquareBoard` class to help with implementing games of this sort. I ended up with roughly the same approach as what we have in Cubeo, so I modified it slightly to use roughly the same conventions. It's meant to be a generic class so there are no game-specific functions in there.
I also added a `reverseNumbers` parameter to the coordinate conversions in `GameBase` because there are quite a few games that have that kind of convention (Reversi and Twixt come to mind).
=> Adding Trax.

locales/en/apgames.json, locales/en/apresults.json, src/games/c1.ts, src/games/index.ts
Adding [C1](https://boardgamegeek.com/boardgame/386986/c1).
=> Adding C1.

src/games/deckfish.ts
=> Sort collected suits

src/games/cubeo.ts
=> Add die count to status in Cubeo
