- locales/en/apgames.json
- src/games/index.ts
- src/games/scaffold.ts
This PR implements [Scaffold](https://boardgamegeek.com/boardgame/360432/scaffold), which seems to be quite a highly requested suggestion from Discord.
The implementation was based on Crossway's code, with some parts taken or heavily inspired by other existing implementations.
The `getGroups` logic was taken from Manalath. This current implementation naively counts the total number of groups for a player, and if placing a stone in one of the four orthogonally adjacent cell reduces the group count, then a followup move must be placed in that location. There is most likely a more efficient algorithm, but I think this logic should work.
> Adding Scaffold.

- locales/en/apgames.json
- src/games/meridians.ts
This should be the full implementation for Meridians now. The only thing that is missing is the optional secondary win condition ([mentioned in the rulesheet](https://cdn.shopify.com/s/files/1/0578/3502/8664/files/Meridians_Wood_EN.pdf?v=1683807023), which is basically an automatic counter so that the game doesn't need to be played out, but it doesn't seem trivial.
> Meridians: Finalising implementation

- locales/en/apgames.json
- locales/en/apresults.json
- src/games/blooms.ts
- src/games/index.ts
Adding [Blooms](https://boardgamegeek.com/boardgame/249095/blooms). This implementation is quite unconventional when it comes to the colours and the UX.
Traditionally, Player 1 uses blue and black, and Player 2 uses red and yellow. In order to be consistent with Abstract Play's colour interface, I made the colours correspond with the colours assigned for players 1 and 2, and the second colours are the same colours with an opacity of 0.35. There is also a ring around the pieces to further differentiate it from the normal piece.
In terms of the UX, having a stash makes it very annoying to place pieces, so I opted for the ability to swap the colours if you tapped on the placed piece.
Board sizes 6 (default), 8 and 10 are included here.
For the threshold score, I went with the simple X(n) = …
> Added Blooms.

- src/games/blooms.ts
- src/games/mattock.ts
I'm trying a #FFF background at 1.0 opacity to see if it improves the visibility of the board in dark mode for Mattock and Blooms.
Also added the "random-start" flag for Mattock.
> Try white background to make certain renders hopefully look better in dark mode.

- locales/en/apgames.json
- src/games/catchup.ts
- src/games/mattock.ts
- src/games/trike.ts
Sort moves based on coordinates so that "a10" comes after "a9", which is necessary on boards larger than hexhex-5. I still have no idea why the performance on the live server for hexhex-6 is so bad when every move is instantaneous on the local playground.
While I'm at it, I also added the option to remove possible move indicators for Trike without disabling last move indicators completely.
Also removed the white background for flood fill in Mattock that I added in the previous PR because it covers the hex outlines.
> Catchup: Fixed sorting for larger boards

- locales/en/apgames.json
- locales/en/apresults.json
- src/games/index.ts
- src/games/veletas.ts
- src/schemas/moveresults.d.ts
- src/schemas/moveresults.json
Adding [Veletas](https://boardgamegeek.com/boardgame/151224/veletas).
Move generation during movement phase is impossible (placing 4 and 5 stones on the board). I've bypassed the move checker for the first two moves, and added a regex validator to hopefully catch all potential bad moves. I also overrode the random move generation to accommodate this lack of move list.
I'll fix Catchup in a separate PR once we see if this works.
> Added Veletas

- src/games/blooms.ts
- src/games/catchup.ts
For multi-placement games, it feels like it's easy to lose track of what stones have been placed. In the implementations of these games, clicking on placed-but-not-submitted stones potentially do something (remove stones in Catchup, and swap colours in Blooms). I'm attempting a yellow flood fill to hopefully make it easier to keep track of the current move.
> Add current move highlight using yellow flood fill.

- locales/en/apgames.json
- src/games/blooms.ts
- src/games/catchup.ts
- src/games/hex.ts
Adding the variantGroups description for default board sizes for the games that I know.
Adjusted the marker opacity of Catchup and Blooms.
I think Hex is surprisingly popular. Size-19 seems to be of interest to the community, so let's add it.
> Adding some variantGroups descriptions, and Hex size-19

- src/games/onager.ts
As per discussion on Discord, I'm readding the deepclones just for safe measure. I don't think it's necessary, but one of the game records on the dev server was lost on game end during testing for some reason, and these stacks that are shared across moves were suspect. There is minimal overhead anyway, so until the root cause is found, we can leave this here. Hopefully we won't run into any issues.
> Onager: Add deepclone

- src/games/cannon.ts
- src/games/tumbleweed.ts
The 0.7 opacity is unnecessary and it makes it hard to see for lighter colours. I left out that parameter for Tumbleweed by accident, so that's probably why nobody complained before.
> Cannon & Tumbleweed: Remove opacity for threatened piece highlight

- src/games/conhex.ts
Fixed a bug where the (1,1) space was not part of the west boundary of the horizontal player.
> ConHex: Fix error in west line.

- src/common/graphs/hex-slanted.ts
- src/common/graphs/hextri.ts
- src/common/graphs/snubsquare.ts
- src/common/graphs/sowing-no-ends.ts
- src/common/graphs/square-diag.ts
- src/common/graphs/square-fanorona.ts
- src/common/graphs/square-orth.ts
- src/common/graphs/square.ts
- src/games/_base.ts
In the `algebraic2coords` methods, we are using `parseInt(num, 10)`. This looks for the first number, so if `num === "2,a6,b4"`, it gets parsed such that `y === 2`. Since a lot of our validation involves a try catch block to see if the `algebraic2coords` returns an error, the result is a lot of false negatives in the validation. If we used `Number` instead, I believe it returns NaN when it's not purely a number, meaning the validation becomes slightly more robust without any additional checks aside from if `num === ""` (as `Number("") === 0`). But since `Number` is more efficient than `parseInt`, it will likely be a net performance improvement anyway (unbenchmarked claim). Another caveat is that nulls and undefined values will also return 0 when `parseInt` returns NaN, but I did not check …
> Proposal: Use `Number` instead of `parseInt`.

- src/games/catchup.ts
There was a request to fill the space in Catchup instead of to put a piece. I'm trying a hex-pointy that is scaled to 1.35.
> Catchup: Try using hex-pointy instead of piece

- src/games/tafl.ts
- src/games/tafl/ruleset.d.ts
- src/games/tafl/ruleset.json
- src/games/tafl/settings.ts
- Renamed Tafl to Hnefatafl
- Simplified escape fort rule so that it no longer checks if the fort is unbreakable. This is because I wanted it to be consistent with the encirclement rule, and it's slightly more complicated to check if encirclement is unbreakable because I need to care about what's on the "inside" vs "outside" the encirclement.
- The win for encirclement and escape fort is checked after the mover's turn, so the opponent gets one chance to break the encirclement/fort before the game ends.
- Added `inCheck` because it's part of the traditional rules, but checkmate is not enforced. The King still has to make the escape or be captured.
> Hnefatafl: some changes

- locales/en/apgames.json
- src/games/tafl.ts
- src/games/tafl/ruleset.d.ts
- src/games/tafl/ruleset.json
- src/games/tafl/settings.ts
The term "historical" is not actually that descriptive, and I don't really want to make claims about it being the only historical variant, or if it's the "correct" historical ruleset; just that it's the rules as described by Linnaeus. The way it's implemented, the variant name fully defines the ruleset, so if we want to later implement a different "historical" variant, it could be a bit confusing.
> Hnefatafl: Rename historical to linnaean.

- src/games/reversi.ts
Turns out that in the very vast literature, it is much more common for the numbering to start from the top. There are ongoing games, but I think that this change will be relatively harmless since it will just mirror the position vertically for those games. The only thing is that the opening positions for the games that have already started will be mirrored, but I think it's a change that's worth doing in the long run.
Testing this in the dev server first for ongoing test games.
> Reversi: Reverse numbers

- locales/en/apgames.json
- src/games/blockade.ts
Changing the walls on the board to be recorded as a map to playerid instead of just a set. It doesn't make a difference in gameplay, but sometimes it's just interesting to be reminded of who placed a particular wall. Not backwards compatible with previous version because of data structure change.
I note that there isn't a way to pass the renderer options to `getPlayerStash` to adjust the colours accordingly. I wanted to set the colour of the horizontal and vertical bars to #000000, but it doesn't display very well in dark mode. Left it as player 3 colour for now.
> Blockade: Optionally allow walls to be displayed in different colours.

- src/games/archimedes.ts
- src/games/breakthrough.ts
- src/games/courtesan.ts
- src/games/epam.ts
- src/games/furl.ts
- src/games/hens.ts
- src/games/lielow.ts
- src/games/loa.ts
- src/games/monkey.ts
- src/games/reversi.ts
- src/games/tafl.ts
Adding material balance count for
* Archimedes
* Breakthrough
* King & Courtesan
* Epaminondas
* Furl
* Hens and Chicks
* Lielow
* Lines of Action
* Monkey Queen
It was added to Hnefatafl in a previous commit.
Some things to note:
* I found a weird line in Furl where it was adding moves to the board. Made this discovery when there were  It's likely an older code that was left there. Didn't have any impact on the games, but the older records has a bit of junk in them... Games started with an older version will not have the piece count display because of that.
* I decreased the buffer size for Lielow. I don't think it's a move that people make often anyway. It's just there to make the game rules elegant to work with the no-pass rule.
* Not relevant, but Reversi was missing chat messages for …
> Piece count

- locales/en/apgames.json
- src/games/tafl.ts
- src/games/tafl/settings.ts
Total Hnefatafl is a combination of Fetlar, Copenhagen and Berserk rules. It is a strong armed king with corner escape rules, with shield wall captures, exit forts, and encirclement win. Berserk capture is enabled and the king can make a berserk escape. Repetitions result in a draw.
> Hnefatafl: Add total variant

- locales/en/apgames.json
- locales/en/apresults.json
- src/games/index.ts
- src/games/pente.ts
Adding the game [Pente](https://boardgamegeek.com/boardgame/1295/pente).
Testing swap2 implementation as well. I'm implementing a custom pie because I think these games can have different opening protocols, and so the metarule pie will not be sufficient. I doubt the utility of using that metarule for this case too since the pies can be so complex, unlike the other first-move-only pies.
Thought I'd start with the more complex one, but I'm likely to add Gomoku, Connect6 and maybe even Renju. I may update this code as I gain a better understanding of what is required, so I propose that we hold off on the release for this game for now until this family of games is complete.
Currently I'm using "pass" to indicate swap because it has a dedicated button, but maybe we could use a different …
> Adding Pente.

- src/games/flume.ts
I'm not sure how this worked before, but it seems like there's an error here...
Whenever the user tries to submit multi-placements, the validator complains that it is not able to find the cell.
> Fix Flume validation

- src/games/_base.ts
- src/games/anache.ts
- src/games/asli.ts
- src/games/ataxx.ts
- src/games/ayu.ts
- src/games/fanorona.ts
- src/games/gonnect.ts
- src/games/hexentafl.ts
- src/games/irensei.ts
- src/games/margo.ts
- src/games/tafl.ts
I think the previous `stateCount` implementation was delayed by one move because it was checking for repetition with reference to the last item in the stack. But the `stateCount` method is called in `checkEOG`, which is called before`saveState`, so the new `board` and `currplayer` are not yet committed at that point. This means that once the repetition has been detected, it forced the next player to make one extra move before actually ending the game.
While making this fix, I also generalised what to check. Now, we just give the actual objects that we want to check against the properties in the state as a `Map<string, any>`, where the key is the name of the property and the value is the object to check. If we wish to check for situational supreko, we feed in the `board` and `currplayer`. …
> Fix stateCount and generalised the implementation.

- src/games/terrace.ts
Don't know if there's a good reason for it, but the results are not loaded into the game object, so move annotations aren't being displayed.
> Terrace: Load the results

- src/games/moonsquad.ts
I decided to combine the two into a single PR because I'm lazy, but the changes are in different commits so we can undo them or decouple them as long as the changes aren't squashed.
The first change is some QoL improvements to the click handler to allow deselecting. Namely, we can click on selected squads to deselect them, or click on the same ore type to remove squad move (or change ore type if clicking on a different ore), and when moving squads, you can click on the start or end positions to undo a movement.
The second change is something that has been bugging me. The ore is usually in uppercase, but because we do m.toLowerCase(), it actually makes the ore also become lower case in the squad move notation (e.g. -b(d5-d4,e6-g4) instead of -B(d5-d4,e6-g4)). It doesn't seem like there are …
> Moon Squad: QoL changes and move notation update

- src/common/index.ts
- src/common/stackset.ts
- src/games/hula.ts
- test/games/hula.test.ts
Updated Hula to comply with the rules change in case of simultaneous loops.
- New (more correct) algorithm to find the shortest loops
- Winner is the shortest loop. If equal, the loop with fewer neutrals. If equal, p2 always wins. I've tested each case locally.
> Hula rules update

- locales/en/apgames.json
- src/games/cubeo.ts
- src/games/cubeo/board.ts
I added Cubeo "dice" variants to play up to 8, 10, or 12 dice: 
```
"#dice": {
"name": "Default die size (d6)",
"description": "Each player has six d6, and the merge goal is 7."
},
"d8": {
"name": "d8",
"description": "Each player has eight 8-sided, yet cubical, dice, and the merge goal is 9."
},
"d10": {
"name": "d10",
"description": "Each player has ten 10-sided, yet cubical, dice, and the merge goal is 11."
},
"d12": {
"name": "d12",
"description": "Each player has twelve 12-sided, yet cubical, dice, and the merge goal is 13."
}
```
I took out the 7 and 9 variants when adding 10 and 12.   The 7/8/9 version was less of a code change and is possibly less buggy than the second commit.  (Not that I think there are still bugs, but just in case something comes up.)
> Cubeo variants

- src/games/gess.ts
I think the other no-designer games should be marked as Traditional or some such, or the Designer title omitted from the front end meta game page when the field is omitted.  But this one was an easier fix.
> Add designer of Gess

- src/games/deckfish.ts
My attempt to "handle" a double deck by ignoring it didn't work as well as expected, so I had to breaking-change my data model a bit.
> Breaking fix to ersatz double decktet display issues in Deckfish

- src/games/deckfish.ts
Got bitten by a javascript WAT I wasn't expecting to persist in typescript.
> Fix scoring and validation bugs in Deckfish
